"""Source adapters and deterministic local fixture inputs."""

from .synthetic import (
    FixtureValidationError,
    LoadedSyntheticFixture,
    RejectedFact,
    SyntheticFact,
    canonical_payload_digest,
    load_synthetic_fixture,
)
from .wyscout import (
    AdmittedArchiveMember,
    ArchiveAdmission,
    DownloadOpener,
    ScopeExcludedArchiveMember,
    VerifiedDownload,
    WyscoutAcquisitionResult,
    WyscoutArchiveError,
    WyscoutConfigError,
    WyscoutDownloadError,
    WyscoutManifestError,
    WyscoutRedirectAuthority,
    WyscoutSourceConfig,
    WyscoutSourceError,
    WyscoutSourceObject,
    acquire_wyscout_v5,
    admit_archive,
    download_source_object,
    load_wyscout_source_config,
)

__all__ = [
    "AdmittedArchiveMember",
    "ArchiveAdmission",
    "DownloadOpener",
    "FixtureValidationError",
    "LoadedSyntheticFixture",
    "RejectedFact",
    "ScopeExcludedArchiveMember",
    "SyntheticFact",
    "VerifiedDownload",
    "WyscoutAcquisitionResult",
    "WyscoutArchiveError",
    "WyscoutConfigError",
    "WyscoutDownloadError",
    "WyscoutManifestError",
    "WyscoutRedirectAuthority",
    "WyscoutSourceConfig",
    "WyscoutSourceError",
    "WyscoutSourceObject",
    "acquire_wyscout_v5",
    "admit_archive",
    "canonical_payload_digest",
    "download_source_object",
    "load_synthetic_fixture",
    "load_wyscout_source_config",
]
